apiVersion: v1
kind: Service
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  ports:
    - port: 80
  selector:
    app: drupal
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: frontend
    spec:
      containers:
      - image: bitnami/drupal
        name: drupal
        env:
        - name: MARIADB_HOST
          value: drupal-mysql
        - name: DRUPAL_DATABASE_USER
          value: dbuser
        - name: DRUPAL_DATABASE_NAME
          value: drupaldb
        - name: DRUPAL_DATABASE_PASSWORD
          value: gurpreet
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - mountPath: /var/www/html/
          name: drupal-persistent-storage
      volumes:
      - name: drupal-persistent-storage
        persistentVolumeClaim:
          claimName: efs-drupal-pvc