secretGenerator:
    - name: mysql-pass
      literals:
      - password=Z3VycHJlZXQ= # password encoded in  Base64
resources:
    - create-efs-provisioner.yaml
    - create-rbac.yaml
    - create-storage.yaml
    - deploy-drupal-mysql.yaml 
    - deploy-drupal.yaml